deploy:
	GIT_USER=cristianemoyano \
	  CURRENT_BRANCH=master \
	 npm run publish-gh-pages

start:
	npm start

local:
	python -m webbrowser "http://localhost:3000/arduino_docs/"

prod:
	python -m webbrowser "https://cristianemoyano.github.io/arduino_docs/"